const adjetivosPositivos = {
    A: ['Amazing - incrível', 'Adventurous - aventureiro', 'Affectionate - afetuoso'],
    B: ['Brilliant - brilhante', 'Brave - corajoso', 'Bright - inteligente'],
    C: ['Cunning - astuto', 'Creative - criativo', 'Compassionate - compassivo'],
    D: ['Diligent - diligente', 'Dependable - confiável', 'Daring - ousado'],
    E: ['Enthusiastic - entusiasmado', 'Energetic - energético', 'Empathetic - empático'],
    F: ['Friendly - amigável', 'Fearless - destemido', 'Faithful - fiel'],
    G: ['Generous - generoso', 'Grateful - grato', 'Gregarious - sociável'],
    H: ['Honest - honesto', 'Humble - humilde', 'Hopeful - esperançoso'],
    I: ['Intelligent - inteligente', 'Insightful - perspicaz', 'Imaginative - imaginativo'],
    J: ['Joyful - alegre', 'Just - justo', 'Jubilant - jubiloso'],
    K: ['Kind - gentil', 'Knowledgeable - conhecedor', 'Keen - afiado'],
    L: ['Loyal - leal', 'Loving - amoroso', 'Lively - vivo'],
    M: ['Motivated - motivado', 'Mature - maduro', 'Mindful - atento'],
    N: ['Noble - nobre', 'Nurturing - nutritivo', 'Neat - organizado'],
    O: ['Optimistic - otimista', 'Observant - observador', 'Open-minded - mente-aberta'],
    P: ['Patient - paciente', 'Passionate - apaixonado', 'Persistent - persistente'],
    Q: ['Quick - rápido', 'Quiet - quieto', 'Quirky - excêntrico'],
    R: ['Reliable - confiável', 'Resilient - resiliente', 'Respectful - respeitoso'],
    S: ['Strong - forte', 'Sincere - sincero', 'Sympathetic - simpático'],
    T: ['Thoughtful - pensativo', 'Trustworthy - confiável', 'Talented - talentoso'],
    U: ['Understanding - compreensivo', 'Upbeat - animado', 'Unique - único'],
    V: ['Versatile - versátil', 'Vibrant - vibrante', 'Valiant - valente'],
    W: ['Wise - sábio', 'Warm - caloroso', 'Willing - disposto'],
    X: ['Xenial - hospitaleiro', 'Xpressive - expressivo', 'Xtraordinary - extraordinário'],
    Y: ['Youthful - jovial', 'Yielding - flexível', 'Yearning - desejoso'],
    Z: ['Zealous - zeloso', 'Zany - engraçado', 'Zesty - animado'],
};

const dicionarioVerbos = {
    acclaim: "aclamar, aplaudir, saudar",
    ace: "acertar",
    achieve: ["conquistar", "alcançar"],
    acknowledge: "reconhecer",
    acquiesce: "aceitar, concordar com",
    advise: "aconselhar",
    aim: "mirar",
    aired: "exibido",
    aligns: "alinhar",
    allows: "permitir",
    annoy: "irritar",
    appeal: ["apelar, recorrer", "agradar"],
    argue: ["discutir", "argumentar"],
    arrange: ["arranjar", "organizar", "arrumar"],
    assemble: "montar, reunir",
    assume: "presumir",
    attend: ["atender", "participar", "assistir"],
    attest: "atestatar",
    avoid: "evitar",
    beg: ["mendigar", "implorar"],
    begin: "começar",
    behave: ["agir", "comportar-se"],
    benefit: "beneficiar",
    blink: "piscar",
    bloom: "florescer",
    bluff: "enganar, iludir",
    boast: "vangloriar-se, ostentar",
    bother: ["incomodar", "aborrecer"],
    bounce: ["quicar", "saltar"],
    bring: "trazer",
    bump: ["esbarrar", "bater"],
    cater: "suprir",
    cause: "causar",
    cease: ["cessar", "deixar de"],
    chase: "perseguir",
    cheat: ["enganar", "trapacear", "trair"],
    chew: "mastigar",
    claim: "reivindicar",
    comb: "pentear",
    concern: ["interessar", "preocupar"],
    consider: "considerar",
    convey: ["comunicar", "transmitir"],
    cope: "lidar, coperar > com coisas",
    crack: "quebrar",
    cram: ["empinar", "amontoar"],
    crawl: "rastejar",
    criticize: "criticar",
    curse: "xingar",
    customize: "customizar",
    daunting: ["assombrar", "amedrontar"],
    deceive: "enganar",
    deepen: "aprofundar",
    defaces: "desfigurar, estragar",
    defeat: "derrotar",
    deny: "negar",
    depict: ["retratar", "descrever", "representar"],
    devise: ["conceber", "inventar"],
    differ: "diferir",
    dig: ["escavar", "cavar"],
    donate: "doar",
    drop: ["derrubar", "cair"],
    dump: "jogar fora, despejar",
    elongate: "alongar",
    encompass: "abrangir",
    ensure: "garantir",
    entail: ["implicar", "vincular"],
    escalates: ["escalar", "aumentar"],
    evaluate: "avaliar",
    evolve: "evoluir",
    excel: ["sobressair", "notabilizar-se"],
    fail: "falhar",
    feed: "alimentar",
    fill: "preencher",
    fine: "multar",
    fire: ["disparar", "demitir", "incendiar"],
    flee: "fugir",
    flow: ["fluir", "correr"],
    fly: "voar",
    foster: ["fomentar", "nutrir", "alimentar"],
    fulfill: ["completar", "cumprir"],
    gauge: ["medir", "aferir", "calibrar"],
    give: ["dar", "(gave - simple p. / given p. participle)"],
    glance: ["olhar (de relance)", "relanciar"],
    grab: ["agarrar", "roubar"],
    greet: ["cumprimentar", "saudar"],
    grumble: "resmungar",
    hang: ["pendurar", "enforcar", "suspender"],
    harass: ["molestar", "incomodar"],
    harm: "ferir",
    hinder: "impedir",
    hire: "contratar",
    hold: ["segurar", "manter (simple p - held)"],
    hums: "cantarolar",
    hunt: "caçar",
    idolize: "idolatrar",
    impair: "prejudicar",
    impose: "impor",
    improve: "melhorar",
    infer: ["subentender", "inferir", "deduzir"],
    inflict: "inflingir",
    intend: "pretender",
    jeopardise: ["comprometer", "pôr em risco"],
    join: "juntar-se",
    kick: "chutar",
    lack: "faltar",
    land: ["aterrar", "pousar", "desembarcar", "aterrissar"],
    last: "durar",
    launch: "lançar",
    lead: ["liderar", "conduzir"],
    lend: "emprestar",
    lighten: "iluminar",
    loosen: "relaxar",
    maintain: "manter",
    measure: ["calcular", "avaliar", "medir"],
    mend: ["remendar", "consertar"],
    moan: "gemer",
    mock: ["zombar", "escárnio"],
    numble: "resmungar (quietly)",
    mutter: "murmurar (with mouth almost closed)",
    notice: "perceber",
    outgrow: "crescer, superar",
    overcome: ["superar", "vencer", "dominar", "triunfar"],
    overestimate: "superestimar",
    overrate: ["confiar demais", "exagerar o valor de"],
    owe: "dever",
    pay: "pagar",
    pet: "acariciar, afagar",
    pinch: "beliscar",
    postpone: "adiar",
    pound: ["socar", "esmagar"],
    pretend: "fingir",
    prevent: "prevenir",
    prioritize: "priorizar",
    puke: "vomitar",
    pursue: ["perseguir", "buscar"],
    raise: ["levantar", "elevar", "aumentar"],
    recap: ["revisar", "recapitular"],
    recognize: "reconhecer",
    rectify: ["retificar", "corrigir", "ajustar"],
    refuse: "recusar",
    reinforce: ["reforçar", "fortalecer"],
    relieve: "aliviar",
    rely: ["confiar", "contar com", "ter confiança"],
    remain: ["permanecer", "restar"],
    remedy: ["remediar", "reparar", "solucionar"],
    rent: "alugar",
    repack: "reembalar",
    reshape: "remodelar",
    resell: "revender",
    restrain: "restringir",
    rid: "livrar",
    rob: ["roubar", "(past > robbed)"],
    scatter: ["espalhar", "dispersar"],
    see: ["ver", "(past > saw)"],
    shake: ["tremer", "(past > shook)"],
    shed: ["mudar", "verter", "derramar"],
    shift: ["transferir", "alterar", "substituir"],
    shop: "comprar",
    shrink: ["encolher", "diminuir"],
    shuffle: "embaralhar",
    skin: ["rasgar", "ralar"],
    skip: "pular",
    slip: "escorregar",
    solve: "resolver",
    soothe: "acalmar",
    spare: ["poupar", "economizar"],
    spoils: ["prejudicar", "estragar"],
    spread: "espalhar",
    stand: ["ficar", "(past > stood)"],
    steer: ["dirigir", "conduzir"],
    stick: ["grudar", "colar"],
    stiffen: "endurecer",
    strengthen: "fortalecer",
    struggle: "lutar",
    stumble: "tropeçar",
    stun: ["atordoar", "chocar"],
    stutter: "gaguejar",
    sue: ["processar", "acionar"],
    summarize: "resumir",
    supply: "fornecer",
    surrender: ["render-se", "renunciar"],
    surround: "cercar",
    sway: "balançar",
    sweep: "varrer",
    swoon: "desmaiar (por grande causa de euforia)",
    teach: ["ensinar", "(past > taught)"],
    terminate: ["terminar", "encerrar"],
    think: ["pensar", "(past > thought)"],
    threaten: "ameaçar",
    thrive: ["florescer", "prosperar"],
    tie: ["amarrar", "empatar"],
    tread: ["pisar", "(past > trod, trodden)"],
    troubleshoot: "solucionar problemas, quebrar o galho",
    twirl: ["girar", "enrolar"],
    underestimate: "subestimar",
    undergo: ["submeter-se a", "sofrer", "passar por (past > undergone)"],
    unscramble: "decifrar, desembaralhar",
    unveil: "desvendar, revelar",
    unwind: "descontrair",
    valuate: "avaliar",
    vary: "variar",
    warn: ["avisar", "prevenir"],
    wave: "acenar",
    widen: ["ampliar", "alargar", "estender"],
    yell: "gritar",
}

const dicionarioSubstantivos = {
    "accent": "sotaque",
    "accessories": "acessórios",
    "accomplishment": "realização, o feito",
    "acquaintances": "conhecido",
    "addiction": "vício",
    "address": "endereço",
    "advice": "conselho",
    "ageism": "preconceito de idade",
    "aid": "ajuda, auxílio",
    "airfare": "passagem aérea",
    "alacrity": "entusiasmo",
    "alias": "apelido",
    "allowance": "mesada",
    "alumni": "ex-alunos",
    "amount": "quantia",
    "anger": "raiva",
    "antiques": "antiguidades",
    "antiquity": "antiguidade",
    "asset": "ativo, posse",
    "attendance control": "controle de presença",
    "augmentation": "acréscimo, aumento",
    "avant-garde": "vanguarda",
    "awareness": "consciência, conhecimento",
    "backwards": "ao contrário/para trás",
    "bearing": "consequência",
    "beholder": "espectador",
    "beliefs": "crenças",
    "belongings": "pertences",
    "bench": "tribunal, banco, longo assento para muitas pessoas",
    "betrayal": "traição",
    "biography": "biografia",
    "bitterness": "amargura",
    "blanks": "espaços em branco",
    "bluff": "blefe, falésia",
    "bond": "ligação, vínculo",
    "boyish": "juvenil",
    "brainstorm": "chuva de ideias, ideia genial",
    "brand": "marca",
    "break": "troco, falha, recreio, fuga, pausa",
    "brat": "pirralho, fedelho",
    "breeding": "reprodução",
    "bristle": "pelos",
    "broadcast": "transmissão",
    "buck": "dinheiro, grana",
    "bully": "valentão",
    "burial": "enterro",
    "buzzing": "zumbido, vibração",
    "captivity": "cativeiro",
    "cartoons": "desenhos animados",
    "catering": "refeições",
    "chamber": "câmara, sala",
    "chaos": "caos",
    "characters": "personagens",
    "childhood": "infância",
    "chores": "tarefas",
    "citizen": "cidadão",
    "clearance": "liquidações / liberação, separação",
    "clow": "comporta, represa",
    "colleague": "colega",
    "comma": "vírgula",
    "commitment": "compromisso",
    "comradeship": "camaradagem",
    "cost": "preço, custo",
    "crops": "cultivo, colheita",
    "cues": "pistas, palpite",
    "culprit": "culpado",
    "culture": "cultura",
    "curiosities": "curiosidades",
    "curly braces": "chaves (pontuação)",
    "daffodils": "narcisos",
    "daisy": "margarida",
    "dam": "barragem, açude, represa",
    "daughter": "filha",
    "deals": "promoções / negociação, ato",
    "dean": "reitor, sacerdote",
    "deed": "ato, feito, obra, ação",
    "deleight": "deleite",
    "desire": "desejo, vontade",
    "disposal": "disposição",
    "disposition": "disposição, caráter",
    "dozen": "dúzia",
    "draw": "empate",
    "drawback": "desvantagem",
    "drawing": "desenho",
    "drizzle": "garoa",
    "duty": "dever, obrigação, imposto",
    "dwarf": "anão, gnomo",
    "ease": "facilidade",
    "effort": "esforço",
    "elections": "eleições",
    "elementary school": "escola primária",
    "enforcement": "aplicação, execução",
    "enrollment": "inscrição, matrícula",
    "equipment": "equipamento",
    "errand": "tarefa",
    "essay": "ensaio, redação",
    "esteem": "estima",
    "etching": "gravura",
    "expenses": "despesas",
    "fad": "mania, novidade, moda",
    "failure": "falha, fracasso",
    "fantasy": "fantasia",
    "farewell": "despedida",
    "fault": "culpa",
    "feast": "banquete, festa",
    "feather": "pena, pluma",
    "features": "características",
    "fees": "honorários, tarifas",
    "fiancé": "noivo (a)",
    "fields": "campos",
    "fine": "multa",
    "folks": "pessoas",
    "foundation": "fundação",
    "freedom": "liberdade",
    "friendliness": "simpatia",
    "fumes": "vapor, fumaça",
    "fur": "pelagem",
    "gag": "piada, mordaça",
    "gal": "garota",
    "gap": "lacuna, espaço, brecha",
    "genres": "gêneros",
    "goatee": "cavanhaque",
    "goods": "mercadorias, itens",
    "grief": "pesar, dor, tristeza",
    "habit": "hábito",
    "hang": "o jeito",
    "hapiness": "felicidade",
    "harvest": "colheita",
    "headquarters": "quartel, centro matriz",
    "hiking": "trilha",
    "hoarders": "acumuladores",
    "hoarding": "acumulação",
    "hoax": "farsa, embuste, trote",
    "homeschooling": "educação escolar em casa",
    "honor": "honra",
    "horror": "terror",
    "household": "doméstico",
    "hunch": "palpite",
    "husk": "casco, casca",
    "hygiene": "higiene",
    "idea": "ideia",
    "illiteracy": "analfabetismo",
    "income": "renda",
    "inmates": "presidiários",
    "insurance": "seguro, proteção",
    "item": "item",
    "ivory": "marfim",
    "juggle": "malabarismo",
    "kindergarten": "jardim de infância",
    "king": "rei",
    "knack": "habilidade, destreza",
    "knowledge": "conhecimento",
    "known": "conhecido",
    "label": "rótulo",
    "labeling": "marcação, rotulação",
    "lack": "falta, necessidade, carência",
    "landlord": "locador, senhorio",
    "landscapes": "paisagens, panoramas",
    "leftovers": "sobras",
    "legacy": "legado",
    "likelihood": "probabilidade",
    "litter collection": "coleta de lixo",
    "living beings": "seres vivos",
    "loan": "empréstimo",
    "lodging": "alojamento, hospedagem",
    "logging": "exploração de madeira",
    "luck": "sorte",
    "luggage": "bagagem",
    "majoring": "majorando, cursando, especializando-se",
    "mankind": "humanidade",
    "manoeuvre": "manobra",
    "mate": "companheiro",
    "maxim": "máximo",
    "merchandise": "mercadoria",
    "meters": "metros",
    "mistake": "erro",
    "misunderstanding": "mal-entendido, equívoco",
    "mockery": "zombaria",
    "mold": "mofo / molde, forma",
    "mud": "lama",
    "mystery": "mistério",
    "myth": "mito",
    "navy": "marinha",
    "neglect": "negligência",
    "next": "próximo, seguinte",
    "nonsense": "absurdo, burrice",
    "novel": "novela, romance",
    "novelty": "novidade",
    "odds": "chances, probabilidade",
    "pace": "ritmo",
    "pack": "pacote (geralmente pequeno)",
    "pal": "amigo, colega",
    "pardon": "perdão",
    "passersby": "transeuntes, 'andantes'",
    "path": "caminho, trajeto",
    "paycheck": "contracheque",
    "peak": "pico",
    "peer": "par",
    "perks": "vantagens",
    "plot": "trama, enredo",
    "plunge": "mergulho, imersão",
    "prejudice": "preconceito",
    "press": "imprensa",
    "profit": "lucro",
    "proof": "comprovação, demonstração",
    "prospects": "perspectivas",
    "proverb": "provérbio",
    "punctuality": "pontualidade",
    "purchases": "compras",
    "quarrel": "briga",
    "queen": "rainha",
    "range": "variação, alcance, faixa",
    "rates": "cotação, taxas",
    "readership": "leitores",
    "relatives": "parentes",
    "reliability": "confiabilidade",
    "rendezvous": "encontro",
    "research": "pesquisa",
    "resources": "recursos",
    "response": "resposta, reação, sensibilidade",
    "retail": "varejo",
    "rivalry": "rivalidade",
    "romance": "romance",
    "runner up": "vice-campeão",
    "sapling": "muda, árvore nova",
    "scarcity": "escassez",
    "scatterbrain": "desatento, distraído",
    "schedule": "cronograma",
    "scoundrel": "canalha, patife, malandro",
    "secret santa": "amigo secreto de natal",
    "self-help": "auto-ajuda",
    "semicolons": "ponto e vírgula",
    "sequel": "sequência",
    "servers": "servidores",
    "sewage": "esgoto",
    "sewing": "costura",
    "shed": "cabana",
    "shell / seashell": "concha",
    "shift": "mudança",
    "shores": "margens, beira-mar",
    "shouts": "gritos",
    "silk": "seda",
    "skills": "habilidades",
    "slavery": "escravidão",
    "soap operas": "novelas",
    "sophistication": "sofisticação",
    "sophomore": "estudante do 2° ano",
    "speech": "discurso, fala",
    "spoof": "paródia",
    "spouse": "cônjuge",
    "sprite": "duende",
    "spyware": "software espião",
    "stab": "facada",
    "staff": "funcionários",
    "stain": "mancha",
    "standard": "padrão",
    "stands": "apoio",
    "statement": "declaração",
    "stench": "fedor",
    "step": "degrau",
    "stick": "graveto, pau, bengala",
    "stimuli": "estímulos",
    "sting": "picada",
    "strain": "variedade",
    "strife": "conflito, contenda, briga",
    "stuff": "coisas",
    "summary": "resumo",
    "sunset": "pôr-do-sol",
    "surface": "superfície",
    "survey": "pesquisa, enquete",
    "tenant": "inquilino",
    "term": "prazo",
    "testimony": "testemunho",
    "thief": "ladrão",
    "thrill": "emoção",
    "tide": "maré",
    "tie": "gravata, laço",
    "tip": "dica",
    "title": "título",
    "tones": "tons",
    "trade": "troca, negociação",
    "trait": "características",
    "treason": "traição",
    "trend": "tendência, moda",
    "trigger": "gatilho",
    "trilogy": "trilogia",
    "truth": "verdade",
    "turnmoil": "turbulência",
    "unwillingness": "falta de vontade, relutância",
    "upstander": "defensor",
    "urge": "impulso, vontade",
    "vacancies": "vagas",
    "value": "valor",
    "visa": "visto",
    "volume": "volume",
    "vowel": "vogal",
    "wealth": "riqueza",
    "welfare": "bem-estar, prosperidade",
    "whereabouts": "paradeiro",
    "whim": "capricho",
    "wiring": "fiação",
    "witness": "testemunha, espectador",
    "wool": "lã",
    "youth": "juventude"

}
